name: ride_on_driver
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+2

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  


  cupertino_icons: ^1.0.6
  flutter_bloc: ^9.0.0
  provider: ^6.1.2
  flutter_screenutil: ^5.9.3
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  intl_phone_field: ^3.2.0
  google_maps_flutter: ^2.10.0
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  firebase_database: ^11.3.4
  google_places_flutter: ^2.0.9
  geocoding: ^3.0.0
  location: ^5.0.3
  flutter_rating_bar: ^4.0.1
  pinput: ^5.0.1
  easy_stepper: ^0.8.5+1
  animated_toggle_switch: ^0.8.4
  equatable: ^2.0.7
  http: ^1.3.0
  bot_toast: ^4.1.3
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  path: ^1.9.0
  pull_to_refresh: ^2.0.0
  permission_handler: ^11.4.0
  geolocator: ^13.0.2
  shared_preferences: ^2.5.2
  audioplayers: ^6.4.0
  url_launcher: ^6.3.1
  cloud_firestore: ^5.6.6
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.17
  flutter_polyline_points: ^2.1.0
  syncfusion_flutter_datepicker: ^30.2.6
  flutter_animate: ^4.5.2
  cached_network_image: ^3.4.1


  connectivity_plus: ^6.1.3
  connection_notifier: ^2.0.1


  intl: ^0.20.2
  shimmer: ^3.0.0
  flutter_html: any
  flutter_background_service: ^5.1.0
  geoflutterfire_plus: ^0.0.24
  onesignal_flutter: ^5.3.3
  flutter_local_notifications: ^17.2.2
  flutter_inappwebview: ^6.1.5
  flutter_keyboard_visibility: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icons.png"
  image_path_ios: "assets/images/app_icons.png"


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/language/
    - assets/tunes/
  



  
  fonts:
    - family: Poppins Black
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
    - family: Poppins Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Poppins Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: Poppins SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Poppins ExtraBold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
    - family:  Poppins Thin
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
